# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/fire/setup-makefiles.sh

AB_OTA_PARTITIONS += \
	gz \
	lk \
	md1img \
	preloader_raw \
	scp \
	spmfw \
	sspm \
	tee